name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.6.0
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - wandb==0.16.0
      - databricks-cli==0.18.0
