name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - hydra-core=1.3.2
  - matplotlib=3.7.2
  - pandas=2.0.3
  - jupyterlab=4.0.9
  - mlflow=2.6.0
  - pip=23.3.1
  - pip:
      - wandb==0.16.0