name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.32.3
  - scikit-learn=1.3.2
  - pandas=2.0.3
  - pip=23.3.1
  - pip:
      - wandb==0.16.0
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
