name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.6.0
  - matplotlib=3.7.2
  - pandas=2.0.3
  - scikit-learn=1.3.2
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - wandb==0.16.0
      - databricks-cli==0.18.0
